---
- name: Some playbook
  hosts: localhost
  tasks:
  - name: Install latest git version
    ansible.builtin.apt:
      name: git
      state: latest

  - name: Git clone
    git:
      repo: "{{ MyRepository }}"
      dest: /data/volume_2/
      clone: yes
      update: yes
